name: CloudFormation Linting scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development

jobs:
  cfn-lint:
    name: cfn lint scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Run cfn-lint
        run: |
          echo "---------------Starting CloudFormation Template Validation using cfn-lint----------------------"
          find cloudFormation -type f \( -name "*.yaml" -o -name "*.yml" \) -not -path "./.github/*" -print0 | xargs -0 -n1 cfn-lint
        continue-on-error: false

      - name: Comment on PR if linting fails
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ CloudFormation linting failed. Please check the workflow logs for details.'
            })
