name: CloudFormation Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  cfn-lint:
    name: Run CloudFormation Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Run cfn-lint
        run: |
          # Find all .yaml and .yml files in the repository and run cfn-lint on them
          find . -type f \( -name "*.yaml" -o -name "*.yml" \) -not -path "./.github/*" -exec cfn-lint {} \;

      - name: Comment on PR if linting fails
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ CloudFormation linting failed. Please check the workflow logs for details.'
            })
